CREATE TABLE users (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100),
	EMAIL TEXT UNIQUE NOT NULL,
	ENTRIES BIGINT DEFAULT 0,
	JOINED TIMESTAMP NOT NULL
);

SELECT * FROM USERS

CREATE TABLE LOGIN (
	ID SERIAL PRIMARY KEY,
	HASH VARCHAR(100) NOT NULL,
	EMAIL TEXT UNIQUE NOT NULL
);

SELECT * FROM LOGIN